name: Build Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r Src/requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --noconsole --clean --log-level=DEBUG main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_LYTE_Build
          path: dist/LYTE.exe

