name: Build Workflow

on: workflow_dispatch

permissions:
  contents: write  # ✅ Required for release creation

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r Src/requirements.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_YTLM
          path: dist/YTLM.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # ✅ Safer, unique
          name: Release ${{ github.run_number }}
          body: |
            Build Release
            This is an automated .exe release.
          files: dist/YTLM.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
