name: Build Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r Src/requirements.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller --clean main.spec

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_YTLM
          path: dist/YTLM.exe
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r Src/requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --clean main.spec
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS_YTLM
          path: dist/YTLM.exe
  build-linux:
    runs-on: linux-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r Src/requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --clean main.spec
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux_YTLM
          path: dist/YTLM.exe

